---
title: "Teaching"
description: |
  Some additional details about Sara's teaching
---

# Students Requesting Letters of Recommendation

Things I will need from you:

- Logistical information: the schools you are applying to, the instructions for submitting, and the deadlines (please give me at least a 2 week notice)

- Information about your goals and trajectory so far: what you are interested in related to the program or job and how does the material in the class(es) that you have had me for fit into that vision for your future.

- Project information: If you completed a project in one of my classes, please remind me of your role, the research question and findings.

# Fall 2023/Spring 2024 - I am on teaching leave.

# Spring 2023 - Bucknell University

**MATH 216 - Stat I**

**MATH 407 - Statistical Design of Scientific Studies**

# Fall 2022 - Bucknell University

**MATH 217 - Stat II**

**FOUN 098-53- Storytelling with Data**

# Spring 2022 - Bucknell University

**MATH 217 - Stat II**

**MATH 304 - Statistical Inference Theory**

[Interactive learnr tutorials and R Markdown templates](https://github.com/sastoudt/StatTheoryLabs)

# Fall 2021 - Bucknell University

**MATH 216 - Stat I**

**MATH 304 - Statistical Inference Theory**
   
# Spring 2021 - Smith College

**SDS 220 - Introduction to Probability and Statistics**

[Interactive learnr tutorials](https://github.com/sastoudt/nudgeStatLabs)

# Fall 2020 - Smith College

**SDS 220 - Introduction to Probability and Statistics**

**SDS/CSC 109 - Communicating with Data**

[Class newsletter](https://buttondown.email/sstoudt/archive)

Read more about the physical data visualization unit [here](https://nebigdatahub.org/data-visualization-beyond-the-screen/).

# NICAR 2020

[Introduction to statistics and R for journalists](https://github.com/sastoudt/NICAR2020_IntroStats)

# Spring 2018 - UC Berkeley

**STAT 198 - Blogging for Data Science, Graduate Student Instructor with Professor Deb Nolan**


See the blogs [here](https://stat198-spring18.github.io/blog/)


# Fall 2017 - UC Berkeley

**STAT 157- Communicating with Data: The art of writing for data science, Graduate Student Instructor with Professor Deb Nolan**


For a snapshot of what we are doing in class, refer to the [tweet-log for the class](https://twitter.com/i/events/1230569061207031808).


