---
title: "Writing"
description: |
  Some additional details about Sara's writing for broader audiences
---

- [Statistical Concepts and Intersectionality](https://mathvoices.ams.org/featurecolumn/2022/07/01/statistical-concepts-and-intersectionality/)

- [The Origins of Ordinary Least Squares Assumptions: Some Are More Breakable Than Others](https://mathvoices.ams.org/featurecolumn/2022/03/01/ordinary-least-squares/) 

- [Why Do We Plot Data Explaner Zine](https://hdsr.mitpress.mit.edu/pub/49opxv6v/release/1)

- [COVID-19 Case Fatality Rate Bias Visual Explainer](https://hdsr.mitpress.mit.edu/pub/p6sdle0t/release/1)

- [Ecology for the Masses Stat Corner](https://ecologyforthemasses.com/author/sstoudt/)

- scripts for 15 episodes of [Study Hall: Data Literacy](https://www.youtube.com/playlist?list=PLNrrxHpJhC8m_ifiOWl1hquDmdgvcviOt) (produced by Arizona State University and the Crash Course team at Complexly

- [Contributions to The Pudding](https://pudding.cool/author/sara-stoudt/): analysis of censorship in Kidz Bop lyrics and past and future "Karen"s

- [BIDS Best Practices Working Group Write-Ups](https://stuartgeiger.com/articles/2018-11-11-BIDS-best-practices/)

- [Blogging Beyond](https://stat198-spring18.github.io/blog/2018/04/18/blogging-beyond): based on Deb Nolan and my experience teaching writing for statistics and data science, a belated response to @KelseyAHE’s request for a blog about student blogs

- [Gender Issues Roundtable Discussion: A Case Study in Uncomfortable Conversations](ttps://bids.berkeley.edu/news/gender-issues-roundtable-discussion-case-study-uncomfortable-conversations): with Kellie Ottoboni, Rebecca Barter, and Ryan Giordano

- [Fixed, Mixed, and Random Effects](https://rlbarter.github.io/Practical-Statistics/2017/03/03/fixed-mixed-and-random-effects/) as part of Rebecca Barter's Practical Statistics group

- [What does probability mean anyway?](https://statsbites.wordpress.com/2018/04/20/what-does-probability-mean-anyway/): Statsbites

- [Four Hours in Manhattan Beach](https://www.latimes.com/lifestyle/story/2019-09-12/four-hours-manhattan-beach): Check out the accompanying map [here](https://observablehq.com/@sastoudt/beach-brunching).

- [CA Governor Gavin Newsom's Social Media](https://www.latimes.com/california/story/2020-05-10/california-governor-gavin-newsom-twitter-facebook-instagram-trump)

- [Tag Yourself](https://logicmag.io/nature/tag-yourself/): Logic Magazine article about community science. 

- [Berkeley Science Review](https://berkeleysciencereview.com/author/sara-stoudt)

- [Covermesongs](http://www.covermesongs.com/author/sarastoudt"): I am a Features writer for the music blog Covermesongs that focuses on, you guessed it, covers.


